"""Error codes for domain model validation.

All error codes are defined as string constants following the pattern E_CATEGORY_DESCRIPTION.
These codes are used in validation errors and map to HTTP status codes per the spec.
"""

# Domain Model Validation Errors
E_POSITION_OUT_OF_BOUNDS = "E_POSITION_OUT_OF_BOUNDS"
E_INVALID_BOARD_SIZE = "E_INVALID_BOARD_SIZE"
E_INVALID_CONFIDENCE = "E_INVALID_CONFIDENCE"
E_INVALID_PRIORITY = "E_INVALID_PRIORITY"
E_INVALID_EVAL_SCORE = "E_INVALID_EVAL_SCORE"
E_INVALID_RISK_LEVEL = "E_INVALID_RISK_LEVEL"
E_INVALID_LINE_TYPE = "E_INVALID_LINE_TYPE"
E_INVALID_LINE_INDEX = "E_INVALID_LINE_INDEX"
E_INVALID_MOVE_TYPE = "E_INVALID_MOVE_TYPE"
E_INVALID_GAME_PHASE = "E_INVALID_GAME_PHASE"
E_MISSING_REASONING = "E_MISSING_REASONING"
E_MISSING_PRIMARY_MOVE = "E_MISSING_PRIMARY_MOVE"
E_MISSING_DATA = "E_MISSING_DATA"
E_MISSING_ERROR_MESSAGE = "E_MISSING_ERROR_MESSAGE"
E_MISSING_GAME_PLAN = "E_MISSING_GAME_PLAN"
E_INVALID_EXECUTION_TIME = "E_INVALID_EXECUTION_TIME"
E_INVALID_TIMESTAMP = "E_INVALID_TIMESTAMP"

# Game Engine Errors
E_MOVE_OUT_OF_BOUNDS = "E_MOVE_OUT_OF_BOUNDS"
E_CELL_OCCUPIED = "E_CELL_OCCUPIED"
E_GAME_ALREADY_OVER = "E_GAME_ALREADY_OVER"
E_INVALID_PLAYER = "E_INVALID_PLAYER"
E_INVALID_TURN = "E_INVALID_TURN"
