"""OpenAPI schema structure validation tests.

Validates that the OpenAPI schema has all required components:
- Info section (title, version)
- All endpoints documented
- Response schemas defined
- HTTP status codes specified
"""

from typing import Any

import pytest

pytestmark = pytest.mark.contract


def test_openapi_schema_has_info_section(openapi_schema: dict[str, Any]) -> None:
    """Test that OpenAPI schema has required info section."""
    assert "info" in openapi_schema, "OpenAPI schema missing 'info' section"
    assert "title" in openapi_schema["info"], "OpenAPI schema missing 'title'"
    assert openapi_schema["info"]["title"] == "Agentic Tic-Tac-Toe API"
    assert "version" in openapi_schema["info"], "OpenAPI schema missing 'version'"
    assert openapi_schema["info"]["version"] == "0.1.0"


def test_openapi_schema_documents_all_endpoints(openapi_schema: dict[str, Any]) -> None:
    """Test that OpenAPI schema documents all required endpoints."""
    paths = openapi_schema.get("paths", {})

    # Health and readiness endpoints
    assert "/health" in paths, "OpenAPI schema missing /health endpoint"
    assert "/ready" in paths, "OpenAPI schema missing /ready endpoint"

    # Game endpoints
    assert "/api/game/new" in paths, "OpenAPI schema missing /api/game/new endpoint"
    assert "/api/game/move" in paths, "OpenAPI schema missing /api/game/move endpoint"
    assert "/api/game/status" in paths, "OpenAPI schema missing /api/game/status endpoint"
    assert "/api/game/reset" in paths, "OpenAPI schema missing /api/game/reset endpoint"
    assert "/api/game/history" in paths, "OpenAPI schema missing /api/game/history endpoint"

    # Agent status endpoints
    assert (
        "/api/agents/{agent_name}/status" in paths
    ), "OpenAPI schema missing /api/agents/{agent_name}/status endpoint"

    # OpenAPI schema endpoint
    # Note: /openapi.json is auto-generated by FastAPI, not a documented endpoint
    # FastAPI automatically serves the OpenAPI schema at /openapi.json
    # We don't need to document it in the paths


def test_openapi_schema_has_response_schemas(openapi_schema: dict[str, Any]) -> None:
    """Test that OpenAPI schema defines all required response schemas."""
    components = openapi_schema.get("components", {})
    schemas = components.get("schemas", {})

    # Core response models
    assert "NewGameResponse" in schemas, "OpenAPI schema missing NewGameResponse"
    assert "MoveResponse" in schemas, "OpenAPI schema missing MoveResponse"
    assert "GameStatusResponse" in schemas, "OpenAPI schema missing GameStatusResponse"
    assert "ErrorResponse" in schemas, "OpenAPI schema missing ErrorResponse"
    assert "AgentStatus" in schemas, "OpenAPI schema missing AgentStatus"

    # Domain models
    assert "GameState" in schemas, "OpenAPI schema missing GameState"
    assert "Position" in schemas, "OpenAPI schema missing Position"


def test_openapi_schema_specifies_http_status_codes(openapi_schema: dict[str, Any]) -> None:
    """Test that OpenAPI schema specifies HTTP status codes for all endpoints."""
    paths = openapi_schema.get("paths", {})

    # Check /health endpoint
    health_path = paths.get("/health", {})
    health_get = health_path.get("get", {})
    assert "responses" in health_get, "/health endpoint missing responses"
    assert "200" in health_get["responses"], "/health endpoint missing 200 status code"

    # Check /ready endpoint
    ready_path = paths.get("/ready", {})
    ready_get = ready_path.get("get", {})
    assert "responses" in ready_get, "/ready endpoint missing responses"
    assert "200" in ready_get["responses"], "/ready endpoint missing 200 status code"
    assert "503" in ready_get["responses"], "/ready endpoint missing 503 status code"

    # Check /api/game/new endpoint
    new_game_path = paths.get("/api/game/new", {})
    new_game_post = new_game_path.get("post", {})
    assert "responses" in new_game_post, "/api/game/new endpoint missing responses"
    assert "201" in new_game_post["responses"], "/api/game/new endpoint missing 201 status code"
    assert "503" in new_game_post["responses"], "/api/game/new endpoint missing 503 status code"

    # Check /api/game/move endpoint
    move_path = paths.get("/api/game/move", {})
    move_post = move_path.get("post", {})
    assert "responses" in move_post, "/api/game/move endpoint missing responses"
    assert "200" in move_post["responses"], "/api/game/move endpoint missing 200 status code"
    assert "400" in move_post["responses"], "/api/game/move endpoint missing 400 status code"
    assert "404" in move_post["responses"], "/api/game/move endpoint missing 404 status code"
    assert "503" in move_post["responses"], "/api/game/move endpoint missing 503 status code"
